### ISSUE TITLE
Refactor: Rename groups to tags

### ISSUE THREAD

**Issue by fsaravia** [attm2x/m2x-gear-s#3]
The groups concept has been deprecated in favor of [tags](https://m2x.att.com/developer/documentation/v2/device#List-Device-Tags).

Add the necessary changes to this library to reflect that change.

**Comment by cb-frontend** [comment]
@knawram is this something that you could look at?

**Comment by vsiul** [comment]
@fsaravia I'll work on this.

**Comment by fsaravia** [comment]
@vsiul thanks!

**Comment by fsaravia** [comment]
@vsiul any news on this front?

**Comment by vsiul** [comment]
@fsaravia ETA is end of next week, sorry for the delay

**Comment by fsaravia** [comment]
Done in https://github.com/attm2x/m2x-gear-s/pull/4
