### ISSUE TITLE
Source code was removed with commit f837c5cbed

### ISSUE THREAD

**Issue by vsiul** [attm2x/m2x-gear-s#7]
@fsaravia I was looking at commit f837c5cbed and noticed you removed the code from the repository. Could you please let me know what's the best place to put the source code back? Right now, the repository has only the documentation and demos

Thanks!

**Comment by fsaravia** [comment]
@vsiul sorry about that! I got confused by other javascript based libraries. I've now added the files back to the repo

**Comment by vsiul** [comment]
@fsaravia Confirmed that the code is back in the repo. Thanks!
